FROM centos:latest

RUN yum update -y && yum upgrade -y
RUN yum install java-1.8.0-openjdk.x86_64 -y
RUN yum -y install unzip
RUN yum -y install wget
COPY tomcat.sh .
RUN sh tomcat.sh
COPY ping-manager.jar /opt/tomcat/webapps/
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
